version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creditcliente-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_H2_CONSOLE_ENABLED: 'true'
    ports:
      - "8080:8080"
    networks:
      - creditcliente-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: creditcliente-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080/creditcliente-api/api
    depends_on:
      - backend
    networks:
      - creditcliente-network

networks:
  creditcliente-network:
    driver: bridge
